name: CI

on: [push]

permissions: read-all

jobs:
  test_action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04, macos-latest, macos-14, macos-15, windows-latest, windows-2022, windows-2025]
    name: Install the cli
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install CLI
        uses: ./
        id: install
      - name: Test CLI
        run: doppler --version
      - name: Self check
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ] || [ "${{ matrix.os }}" == "windows-2022" ] || [ "${{ matrix.os }}" == "windows-2025" ]; then
            doppler --version | findstr "Doppler CLI version"
          else
            doppler --version | grep "Doppler CLI version"
          fi
